############################################################################
# Contest 2026 team 069 fall_detect_app - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = fall_detect_app
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_069_FALL_DETECT_APP)

MAINSRC = fall_detect_main.c

include $(APPDIR)/Application.mk
